In [149]:
import pandas as pd
import numpy as np

In [150]:
movies = pd.read_csv(r"C:\Users\ROHIT RANE\Downloads\archive (1)\tmdb_5000_movies.csv")
credits = pd.read_csv(r"C:\Users\ROHIT RANE\Downloads\archive (1)\tmdb_5000_credits.csv")

In [151]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [152]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [153]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

In [154]:
credits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4803 non-null   int64
 1   title     4803 non-null   object
 2   cast      4803 non-null   object
 3   crew      4803 non-null   object
dtypes: int64(1), object(3)
memory usage: 150.2+ KB

In [155]:
movies.isnull().sum()

budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64

In [156]:
df = movies.merge(credits, on = 'title')

In [157]:
df.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [158]:
df.isnull().sum()

budget                     0
genres                     0
homepage                3096
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
movie_id                   0
cast                       0
crew                       0
dtype: int64

In [159]:
# required columns
# genres, keywords, overview, title, movie_id, cast, crew, vote_average

In [160]:
df = df[['movie_id', 'title', 'genres', 'overview', 'keywords', 'cast', 'crew', 'vote_average']]

In [161]:
df.head(1)

,movie_id,title,genres,overview,keywords,cast,crew,vote_average
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","In the 22nd century, a paraplegic Marine is di...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",7.2

In [162]:
df.isnull().sum()

movie_id        0
title           0
genres          0
overview        3
keywords        0
cast            0
crew            0
vote_average    0
dtype: int64

In [163]:
df.dropna(inplace = True)

In [164]:
df.isnull().sum()

movie_id        0
title           0
genres          0
overview        0
keywords        0
cast            0
crew            0
vote_average    0
dtype: int64

In [165]:
df.head()

,movie_id,title,genres,overview,keywords,cast,crew,vote_average
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","In the 22nd century, a paraplegic Marine is di...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",7.2
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","Captain Barbossa, long believed to be dead, ha...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",6.9
2,206647,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",A cryptic message from Bond’s past sends him o...,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",6.3
3,49026,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",Following the death of District Attorney Harve...,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",7.6
4,49529,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","John Carter is a war-weary, former military ca...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",6.1

In [166]:
import ast

def convert(text):
    l = []
    for i in ast.literal_eval(text):
        l.append(i['name'])
    return l

In [167]:
df['genres'] = df['genres'].apply(convert)

In [168]:
df.head(1)

,movie_id,title,genres,overview,keywords,cast,crew,vote_average
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",7.2

In [169]:
df['keywords'] = df['keywords'].apply(convert)

In [170]:
df.head()

,movie_id,title,genres,overview,keywords,cast,crew,vote_average
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",7.2
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","Captain Barbossa, long believed to be dead, ha...","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",6.9
2,206647,Spectre,"[Action, Adventure, Crime]",A cryptic message from Bond’s past sends him o...,"[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",6.3
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]",Following the death of District Attorney Harve...,"[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",7.6
4,49529,John Carter,"[Action, Adventure, Science Fiction]","John Carter is a war-weary, former military ca...","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",6.1

In [171]:
import ast

def cast_convert(text):
    s = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter < 3:
            s.append(i['name'])
        counter += 1
    return s

In [172]:
df['cast'] = df['cast'].apply(cast_convert)

In [173]:
df.head()

,movie_id,title,genres,overview,keywords,cast,crew,vote_average
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",7.2
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","Captain Barbossa, long believed to be dead, ha...","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",6.9
2,206647,Spectre,"[Action, Adventure, Crime]",A cryptic message from Bond’s past sends him o...,"[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",6.3
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]",Following the death of District Attorney Harve...,"[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",7.6
4,49529,John Carter,"[Action, Adventure, Science Fiction]","John Carter is a war-weary, former military ca...","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",6.1

In [174]:
df['crew'][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [175]:
import ast

def crew_convert(text):
    a = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            a.append(i['name'])
    return a

In [176]:
df['crew'] = df['crew'].apply(crew_convert)

In [177]:
df.head()

,movie_id,title,genres,overview,keywords,cast,crew,vote_average
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],7.2
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","Captain Barbossa, long believed to be dead, ha...","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],6.9
2,206647,Spectre,"[Action, Adventure, Crime]",A cryptic message from Bond’s past sends him o...,"[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes],6.3
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]",Following the death of District Attorney Harve...,"[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan],7.6
4,49529,John Carter,"[Action, Adventure, Science Fiction]","John Carter is a war-weary, former military ca...","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton],6.1

In [178]:
def collapse(text):
    l = []
    for i in text:
        l.append(i.replace(' ', ''))
    return l

In [179]:
df['genres'] = df['genres'].apply(collapse)
df['keywords'] = df['keywords'].apply(collapse)
df['cast'] = df['cast'].apply(collapse)
df['crew'] = df['crew'].apply(collapse)

In [180]:
df.head()

,movie_id,title,genres,overview,keywords,cast,crew,vote_average
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction]","In the 22nd century, a paraplegic Marine is di...","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],7.2
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","Captain Barbossa, long believed to be dead, ha...","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],6.9
2,206647,Spectre,"[Action, Adventure, Crime]",A cryptic message from Bond’s past sends him o...,"[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],6.3
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]",Following the death of District Attorney Harve...,"[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],7.6
4,49529,John Carter,"[Action, Adventure, ScienceFiction]","John Carter is a war-weary, former military ca...","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],6.1

In [181]:
df['overview'] = df['overview'].apply(lambda x : x.split())

In [182]:
df.head()

,movie_id,title,genres,overview,keywords,cast,crew,vote_average
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction]","[In, the, 22nd, century,, a, paraplegic, Marin...","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],7.2
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[Captain, Barbossa,, long, believed, to, be, d...","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],6.9
2,206647,Spectre,"[Action, Adventure, Crime]","[A, cryptic, message, from, Bond’s, past, send...","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],6.3
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[Following, the, death, of, District, Attorney...","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],7.6
4,49529,John Carter,"[Action, Adventure, ScienceFiction]","[John, Carter, is, a, war-weary,, former, mili...","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],6.1

In [ ]:
df['tags'] = df['overview'] + df['genres'] + df['keywords'] + df['cast'] + df['crew']

In [184]:
df.head()

,movie_id,title,genres,overview,keywords,cast,crew,vote_average,tags
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction]","[In, the, 22nd, century,, a, paraplegic, Marin...","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],7.2,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[Captain, Barbossa,, long, believed, to, be, d...","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],6.9,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[Action, Adventure, Crime]","[A, cryptic, message, from, Bond’s, past, send...","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],6.3,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[Following, the, death, of, District, Attorney...","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],7.6,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[Action, Adventure, ScienceFiction]","[John, Carter, is, a, war-weary,, former, mili...","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],6.1,"[John, Carter, is, a, war-weary,, former, mili..."

In [185]:
df = df.drop(columns = ['overview', 'keywords', 'cast', 'crew'], axis = 1)

In [186]:
df.head()

,movie_id,title,genres,vote_average,tags
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction]",7.2,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]",6.9,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[Action, Adventure, Crime]",6.3,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]",7.6,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[Action, Adventure, ScienceFiction]",6.1,"[John, Carter, is, a, war-weary,, former, mili..."

In [187]:
df['tags'] = df['tags'].apply(lambda x : " ".join(x))

In [188]:
df.head()

,movie_id,title,genres,vote_average,tags
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction]",7.2,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]",6.9,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,"[Action, Adventure, Crime]",6.3,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]",7.6,Following the death of District Attorney Harve...
4,49529,John Carter,"[Action, Adventure, ScienceFiction]",6.1,"John Carter is a war-weary, former military ca..."

In [189]:
from sklearn.feature_extraction.text import CountVectorizer

In [190]:
cv = CountVectorizer(max_features = 5000, stop_words = 'english')

In [191]:
vector = cv.fit_transform(df['tags']).toarray()

In [192]:
vector.shape

(4806, 5000)

In [193]:
from sklearn.metrics.pairwise import cosine_similarity

In [194]:
similarity = cosine_similarity(vector)

In [195]:
similarity

array([[1.        , 0.08964215, 0.06071767, ..., 0.02519763, 0.0277885 ,
        0.        ],
       [0.08964215, 1.        , 0.06350006, ..., 0.02635231, 0.        ,
        0.        ],
       [0.06071767, 0.06350006, 1.        , ..., 0.02677398, 0.        ,
        0.        ],
       ...,
       [0.02519763, 0.02635231, 0.02677398, ..., 1.        , 0.07352146,
        0.04774099],
       [0.0277885 , 0.        , 0.        , ..., 0.07352146, 1.        ,
        0.05264981],
       [0.        , 0.        , 0.        , ..., 0.04774099, 0.05264981,
        1.        ]])

In [203]:
df[df['genres'].apply(lambda x : 'ScienceFiction' in x)]

,movie_id,title,genres,vote_average,tags
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction]",7.2,"In the 22nd century, a paraplegic Marine is di..."
4,49529,John Carter,"[Action, Adventure, ScienceFiction]",6.1,"John Carter is a war-weary, former military ca..."
7,99861,Avengers: Age of Ultron,"[Action, Adventure, ScienceFiction]",7.3,When Tony Stark tries to jumpstart a dormant p...
10,1452,Superman Returns,"[Adventure, Fantasy, Action, ScienceFiction]",5.4,Superman returns to discover his 5-year absenc...
14,49521,Man of Steel,"[Action, Adventure, Fantasy, ScienceFiction]",6.5,A young boy learns that he has extraordinary p...
...,...,...,...,...,...
4751,33468,The Brain That Wouldn't Die,"[Horror, ScienceFiction]",4.4,Dr. Bill Cortner (Jason Evers) and his fiancée...
4764,242095,The Signal,"[Thriller, ScienceFiction]",5.8,Three college students on a road trip across t...
4770,326576,Dawn of the Crescent Moon,"[Thriller, Drama, ScienceFiction]",2.0,A group of college students travel to a small ...
4793,86304,All Superheroes Must Die,"[ScienceFiction, Thriller]",4.2,"Masked vigilantes Charge (Jason Trost), Cutthr..."
4802,14337,Primer,"[ScienceFiction, Drama, Thriller]",6.9,Friends/fledgling entrepreneurs invent a devic...

In [197]:
list(enumerate(similarity))

[(0,
  array([1.        , 0.08964215, 0.06071767, ..., 0.02519763, 0.0277885 ,
         0.        ])),
 (1,
  array([0.08964215, 1.        , 0.06350006, ..., 0.02635231, 0.        ,
         0.        ])),
 (2,
  array([0.06071767, 0.06350006, 1.        , ..., 0.02677398, 0.        ,
         0.        ])),
 (3,
  array([0.03984095, 0.02083333, 0.04233338, ..., 0.05270463, 0.05812382,
         0.05661385])),
 (4,
  array([0.18257419, 0.08183171, 0.0831411 , ..., 0.02300219, 0.        ,
         0.        ])),
 (5,
  array([0.11834527, 0.12376844, 0.07544932, ..., 0.02087414, 0.02302046,
         0.02242243])),
 (6,
  array([0.02321817, 0.02428215, 0.02467069, ..., 0.        , 0.02258194,
         0.02199529])),
 (7,
  array([0.17638342, 0.13176157, 0.16064387, ..., 0.        , 0.        ,
         0.        ])),
 (8,
  array([0.06388766, 0.06681531, 0.06788442, ..., 0.05634362, 0.06213698,
         0.06052275])),
 (9,
  array([0.07733089, 0.08087458, 0.0547791 , ..., 0.04546629, 0.02507061,
         0.02441931])),
 (10,
  array([0.11769798, 0.09231862, 0.09379581, ..., 0.02594996, 0.        ,
         0.02787473])),
 (11,
  array([0.08119979, 0.05661385, 0.37387825, ..., 0.0238705 , 0.        ,
         0.        ])),
 (12,
  array([0.09583148, 0.43429952, 0.06788442, ..., 0.        , 0.        ,
         0.        ])),
 (13,
  array([0.04733811, 0.09901475, 0.05029955, ..., 0.02087414, 0.        ,
         0.        ])),
 (14,
  array([0.11428571, 0.11952286, 0.06071767, ..., 0.05039526, 0.055577  ,
         0.        ])),
 (15,
  array([0.05096472, 0.07995027, 0.05415304, ..., 0.        , 0.04956816,
         0.04828045])),
 (16,
  array([0.08226127, 0.0860309 , 0.05827165, ..., 0.07254763, 0.        ,
         0.        ])),
 (17,
  array([0.15026858, 0.26940795, 0.13685938, ..., 0.03786412, 0.        ,
         0.        ])),
 (18,
  array([0.11194342, 0.04682929, 0.04757861, ..., 0.07897985, 0.02177518,
         0.02120949])),
 (19,
  array([0.08728716, 0.11410887, 0.04637389, ..., 0.        , 0.02122382,
         0.02067246])),
 (20,
  array([0.05816751, 0.08111071, 0.04120428, ..., 0.        , 0.        ,
         0.        ])),
 (21,
  array([0.09416472, 0.06565322, 0.06670373, ..., 0.        , 0.        ,
         0.        ])),
 (22,
  array([0.06900656, 0.07216878, 0.03666178, ..., 0.        , 0.        ,
         0.        ])),
 (23,
  array([0.09759001, 0.10206207, 0.13826023, ..., 0.        , 0.        ,
         0.        ])),
 (24,
  array([0.05634362, 0.14731391, 0.05986843, ..., 0.0248452 , 0.10959932,
         0.02668803])),
 (25,
  array([0.03877834, 0.12166607, 0.        , ..., 0.05129892, 0.03771571,
         0.09183979])),
 (26,
  array([0.17142857, 0.11952286, 0.09107651, ..., 0.02519763, 0.        ,
         0.        ])),
 (27,
  array([0.18752289, 0.07354355, 0.04981355, ..., 0.02067246, 0.        ,
         0.02220578])),
 (28,
  array([0.12555296, 0.06565322, 0.1000556 , ..., 0.02768183, 0.        ,
         0.02973505])),
 (29,
  array([0.07100716, 0.04950738, 0.30179727, ..., 0.04174829, 0.04604093,
         0.02242243])),
 (30,
  array([0.07319251, 0.12757759, 0.07777138, ..., 0.        , 0.        ,
         0.        ])),
 (31,
  array([0.15971914, 0.10022297, 0.06788442, ..., 0.02817181, 0.        ,
         0.        ])),
 (32,
  array([0.09116846, 0.09534626, 0.04843595, ..., 0.06030227, 0.02216755,
         0.04318335])),
 (33,
  array([0.10573611, 0.11058147, 0.07490059, ..., 0.        , 0.        ,
         0.        ])),
 (34,
  array([0.        , 0.03608439, 0.        , ..., 0.        , 0.        ,
         0.        ])),
 (35,
  array([0.11065667, 0.11572751, 0.07838618, ..., 0.        , 0.0717496 ,
         0.        ])),
 (36,
  array([0.19194297, 0.0860309 , 0.11654331, ..., 0.02418254, 0.02666904,
         0.        ])),
 (37,
  array([0.08451543, 0.05892557, 0.02993422, ..., 0.0745356 , 0.02739983,
         0.02668803])),
 (38,
  array([0.06289709, 0.10963225, 0.08910918, ..., 0.09245003, 0.06117355,
         0.07944581])),
 (39,
  array([0.08827348, 0.06154575, 0.06253054, ..., 0.02594996, 0.14309095,
         0.        ])),
 (40,
  array([0.05634362, 0.05892557, 0.08980265, ..., 0.0745356 , 0.        ,
         0.        ])),
 (41,
  array([0.14638501, 0.07654655, 0.05184758, ..., 0.        , 0.02372895,
         0.04622502])),
 (42,
  array([0.        , 0.        , 0.        , ..., 0.02151657, 0.        ,
         0.02311251])),
 (43,
  array([0.09759001, 0.05103104, 0.05184758, ..., 0.06454972, 0.        ,
         0.        ])),
 (44,
  array([0.040996  , 0.04287465, 0.04356068, ..., 0.        , 0.        ,
         0.        ])),
 (45,
  array([0.09116846, 0.07150969, 0.02421797, ..., 0.06030227, 0.        ,
         0.        ])),
 (46,
  array([0.17654697, 0.12309149, 0.12506108, ..., 0.10379986, 0.02861819,
         0.        ])),
 (47,
  array([0.21642183, 0.09053575, 0.09198441, ..., 0.03817322, 0.        ,
         0.        ])),
 (48,
  array([0.06776309, 0.09449112, 0.02400077, ..., 0.05976143, 0.        ,
         0.        ])),
 (49,
  array([0.06388766, 0.03340766, 0.03394221, ..., 0.08451543, 0.03106849,
         0.06052275])),
 (50,
  array([0.12344268, 0.09682458, 0.13116517, ..., 0.10886621, 0.03001501,
         0.        ])),
 (51,
  array([0.08586776, 0.04490133, 0.09123958, ..., 0.05679618, 0.02087869,
         0.0203363 ])),
 (52,
  array([0.14494276, 0.09095086, 0.06160411, ..., 0.0255655 , 0.05638839,
         0.        ])),
 (53,
  array([0.04931137, 0.05157106, 0.05239625, ..., 0.02174427, 0.        ,
         0.        ])),
 (54,
  array([0.03524537, 0.03686049, 0.03745029, ..., 0.03108349, 0.        ,
         0.        ])),
 (55,
  array([0.0765559 , 0.08006408, 0.04067259, ..., 0.03375798, 0.01861452,
         0.01813094])),
 (56,
  array([0.14414999, 0.07537784, 0.11487594, ..., 0.        , 0.03504998,
         0.03413944])),
 (57,
  array([0.02898855, 0.09095086, 0.        , ..., 0.        , 0.02819419,
         0.08238526])),
 (58,
  array([0.04733811, 0.07426107, 0.12574886, ..., 0.04174829, 0.        ,
         0.        ])),
 (59,
  array([0.08024109, 0.10489767, 0.04263046, ..., 0.10614898, 0.03902114,
         0.        ])),
 (60,
  array([0.02898855, 0.        , 0.06160411, ..., 0.051131  , 0.        ,
         0.        ])),
 (61,
  array([0.21622499, 0.15075567, 0.07658396, ..., 0.        , 0.        ,
         0.        ])),
 (62,
  array([0.08199201, 0.12862394, 0.13068205, ..., 0.        , 0.        ,
         0.        ])),
 (63,
  array([0.09200874, 0.04811252, 0.04888237, ..., 0.        , 0.        ,
         0.        ])),
 (64,
  array([0.03138824, 0.03282661, 0.        , ..., 0.05536365, 0.        ,
         0.        ])),
 (65,
  array([0.0209657 , 0.02192645, 0.06683189, ..., 0.01849001, 0.04078237,
         0.        ])),
 (66,
  array([0.02492224, 0.13032151, 0.02648136, ..., 0.0439587 , 0.04847862,
         0.07082882])),
 (67,
  array([0.17928429, 0.0625    , 0.06350006, ..., 0.        , 0.        ,
         0.        ])),
 (68,
  array([0.13259871, 0.10400629, 0.070447  , ..., 0.        , 0.        ,
         0.        ])),
 (69,
  array([0.0520266 , 0.05441072, 0.07370846, ..., 0.06117753, 0.01686698,
         0.0164288 ])),
 (70,
  array([0.08119979, 0.05661385, 0.05751973, ..., 0.09548198, 0.        ,
         0.        ])),
 (71,
  array([0.08226127, 0.11470787, 0.05827165, ..., 0.09673017, 0.05333807,
         0.05195243])),
 (72,
  array([0.12344268, 0.09682458, 0.09837388, ..., 0.05443311, 0.        ,
         0.        ])),
 (73,
  array([0.03779645, 0.03952847, 0.        , ..., 0.03333333, 0.        ,
         0.        ])),
 (74,
  array([0.22677868, 0.02635231, 0.02677398, ..., 0.02222222, 0.        ,
         0.        ])),
 (75,
  array([0.09258201, 0.19364917, 0.06558258, ..., 0.02721655, 0.03001501,
         0.        ])),
 (76,
  array([0.07824608, 0.05455447, 0.1385685 , ..., 0.09200874, 0.        ,
         0.        ])),
 (77,
  array([0.01482499, 0.04651303, 0.        , ..., 0.02614882, 0.07209373,
         0.05617667])),
 (78,
  array([0.05345225, 0.0559017 , 0.08519428, ..., 0.02357023, 0.02599376,
         0.        ])),
 (79,
  array([0.07824608, 0.10910895, 0.0554274 , ..., 0.02300219, 0.02536731,
         0.02470831])),
 (80,
  array([0.03450328, 0.03608439, 0.03666178, ..., 0.01521452, 0.        ,
         0.01634301])),
 (81,
  array([0.11710801, 0.08164966, 0.04147807, ..., 0.01721326, 0.05694948,
         0.        ])),
 (82,
  array([0.0833655 , 0.02906191, 0.08858079, ..., 0.04901431, 0.        ,
         0.        ])),
 (83,
  array([0.22190115, 0.07735659, 0.07859438, ..., 0.08697708, 0.04796011,
         0.        ])),
 (84,
  array([0.14564382, 0.10879853, 0.06632365, ..., 0.0183494 , 0.        ,
         0.        ])),
 (85,
  array([0.10631549, 0.1111874 , 0.05648325, ..., 0.03125382, 0.08616848,
         0.03357198])),
 (86,
  array([0.08827348, 0.06154575, 0.03126527, ..., 0.05189993, 0.02861819,
         0.        ])),
 (87,
  array([0.11595421, 0.03031695, 0.03080206, ..., 0.0255655 , 0.        ,
         0.        ])),
 (88,
  array([0.09107651, 0.0952501 , 0.12903226, ..., 0.08032193, 0.        ,
         0.        ])),
 (89,
  array([0.06146576, 0.03214122, 0.01632775, ..., 0.01355193, 0.01494536,
         0.0145571 ])),
 (90,
  array([0.06506   , 0.10206207, 0.03456506, ..., 0.02868877, 0.        ,
         0.        ])),
 (91,
  array([0.15971914, 0.10022297, 0.06788442, ..., 0.02817181, 0.        ,
         0.        ])),
 (92,
  array([0.07100716, 0.07426107, 0.02514977, ..., 0.        , 0.        ,
         0.        ])),
 (93,
  array([0.05039526, 0.05270463, 0.02677398, ..., 0.        , 0.02450715,
         0.0238705 ])),
 (94,
  array([0.16574839, 0.13867505, 0.070447  , ..., 0.        , 0.        ,
         0.06280743])),
 (95,
  array([0.1246112 , 0.0260643 , 0.02648136, ..., 0.02197935, 0.        ,
         0.        ])),
 (96,
  array([0.08964215, 0.09375   , 0.06350006, ..., 0.02635231, 0.02906191,
         0.05661385])),
 (97,
  array([0.07476672, 0.07819291, 0.07944407, ..., 0.13187609, 0.02423931,
         0.        ])),
 (98,
  array([0.08827348, 0.15386436, 0.06253054, ..., 0.        , 0.        ,
         0.        ])),
 (99,
  array([0.02988072, 0.0625    , 0.06350006, ..., 0.        , 0.02906191,
         0.05661385])),
 (100,
  array([0.07377111, 0.03857584, 0.        , ..., 0.06506   , 0.0358748 ,
         0.        ])),
 (101,
  array([0.08827348, 0.06154575, 0.06253054, ..., 0.05189993, 0.02861819,
         0.02787473])),
 (102,
  array([0.11194342, 0.04682929, 0.04757861, ..., 0.01974496, 0.        ,
         0.        ])),
 (103,
  array([0.08877935, 0.09284767, 0.07074999, ..., 0.05872202, 0.        ,
         0.        ])),
 (104,
  array([0.05884899, 0.15386436, 0.06253054, ..., 0.05189993, 0.        ,
         0.        ])),
 (105,
  array([0.1081125 , 0.11306675, 0.15316792, ..., 0.        , 0.03504998,
         0.03413944])),
 (106,
  array([0.04477737, 0.11707323, 0.0237893 , ..., 0.01974496, 0.        ,
         0.        ])),
 (107,
  array([0.09200874, 0.07216878, 0.04888237, ..., 0.        , 0.        ,
         0.        ])),
 (108,
  array([0.16903085, 0.05050763, 0.1282895 , ..., 0.04259177, 0.02348557,
         0.0457509 ])),
 (109,
  array([0.07968191, 0.16666667, 0.08466675, ..., 0.07027284, 0.        ,
         0.        ])),
 (110,
  array([0.0243975 , 0.02551552, 0.        , ..., 0.02151657, 0.07118685,
         0.02311251])),
 (111,
  array([0.15430335, 0.06454972, 0.06558258, ..., 0.        , 0.12006005,
         0.02923527])),
 (112,
  array([0.09107651, 0.06350006, 0.06451613, ..., 0.08032193, 0.02952693,
         0.        ])),
 (113,
  array([0.05279637, 0.05521576, 0.02804964, ..., 0.02328101, 0.        ,
         0.05001563])),
 (114,
  array([0.05279637, 0.05521576, 0.02804964, ..., 0.        , 0.02567481,
         0.02500782])),
 (115,
  array([0.0541332 , 0.1132277 , 0.02875987, ..., 0.04774099, 0.07897472,
         0.05128205])),
 (116,
  array([0.05714286, 0.02988072, 0.06071767, ..., 0.07559289, 0.0833655 ,
         0.0541332 ])),
 (117,
  array([0.06071767, 0.0952501 , 0.06451613, ..., 0.08032193, 0.        ,
         0.        ])),
 (118,
  array([0.01762268, 0.01843024, 0.        , ..., 0.03108349, 0.        ,
         0.01669451])),
 (119,
  array([0.048795  , 0.05103104, 0.07777138, ..., 0.02151657, 0.02372895,
         0.02311251])),
 (120,
  array([0.        , 0.        , 0.02993422, ..., 0.0248452 , 0.08219949,
         0.05337605])),
 (121,
  array([0.09107651, 0.0952501 , 0.09677419, ..., 0.05354796, 0.02952693,
         0.        ])),
 (122,
  array([0.09583148, 0.13363062, 0.06788442, ..., 0.        , 0.        ,
         0.        ])),
 (123,
  array([0.12198751, 0.05103104, 0.07777138, ..., 0.        , 0.02372895,
         0.02311251])),
 (124,
  array([0.06837635, 0.07150969, 0.04843595, ..., 0.02010076, 0.02216755,
         0.        ])),
 (125,
  array([0.07985957, 0.03340766, 0.05091332, ..., 0.        , 0.01553424,
         0.01513069])),
 (126,
  array([0.11595421, 0.12126781, 0.06160411, ..., 0.051131  , 0.02819419,
         0.        ])),
 (127,
  array([0.13572418, 0.10138839, 0.08240856, ..., 0.03419928, 0.01885786,
         0.        ])),
 (128,
  array([0.        , 0.03227486, 0.09837388, ..., 0.        , 0.        ,
         0.        ])),
 (129,
  array([0.10559274, 0.16564729, 0.11219854, ..., 0.04656202, 0.        ,
         0.        ])),
 (130,
  array([0.03194383, 0.03340766, 0.03394221, ..., 0.02817181, 0.06213698,
         0.06052275])),
 (131,
  array([0.11268723, 0.08838835, 0.08980265, ..., 0.1739164 , 0.02739983,
         0.        ])),
 (132,
  array([0.04558423, 0.07150969, 0.02421797, ..., 0.02010076, 0.02216755,
         0.04318335])),
 (133,
  array([0.03314968, 0.06933752, 0.        , ..., 0.05847053, 0.        ,
         0.        ])),
 (134,
  array([0.13522468, 0.07071068, 0.1796053 , ..., 0.05962848, 0.        ,
         0.        ])),
 (135,
  array([0.        , 0.        , 0.        , ..., 0.02868877, 0.        ,
         0.        ])),
 (136,
  array([0.02548236, 0.07995027, 0.02707652, ..., 0.02247333, 0.09913632,
         0.02414023])),
 (137,
  array([0.03432497, 0.01794895, 0.05470847, ..., 0.01513589, 0.01669219,
         0.0325171 ])),
 (138,
  array([0.08226127, 0.14338483, 0.05827165, ..., 0.02418254, 0.        ,
         0.        ])),
 (139,
  array([0.10821091, 0.09053575, 0.11498051, ..., 0.07634644, 0.04209827,
         0.06150693])),
 (140,
  array([0.05096472, 0.02665009, 0.08122955, ..., 0.08989331, 0.07435224,
         0.02414023])),
 (141,
  array([0.11338934, 0.03952847, 0.04016097, ..., 0.        , 0.        ,
         0.        ])),
 (142,
  array([0.09759001, 0.10206207, 0.06913011, ..., 0.02868877, 0.        ,
         0.        ])),
 (143,
  array([0.06965452, 0.12141073, 0.04934137, ..., 0.06142951, 0.06774581,
         0.06598588])),
 (144,
  array([0.055577  , 0.05812382, 0.05905386, ..., 0.02450715, 0.        ,
         0.        ])),
 (145,
  array([0.0225877 , 0.04724556, 0.02400077, ..., 0.03984095, 0.06590622,
         0.02139802])),
 (146,
  array([0.01725164, 0.0180422 , 0.        , ..., 0.        , 0.10067341,
         0.04902903])),
 (147,
  array([0.06277648, 0.06565322, 0.23346307, ..., 0.02768183, 0.        ,
         0.        ])),
 (148,
  array([0.10573611, 0.07372098, 0.03745029, ..., 0.03108349, 0.        ,
         0.        ])),
 (149,
  array([0.17313746, 0.06790181, 0.0459922 , ..., 0.        , 0.        ,
         0.        ])),
 (150,
  array([0.18869127, 0.0877058 , 0.06683189, ..., 0.09245003, 0.02039118,
         0.01986145])),
 (151,
  array([0.20498002, 0.08574929, 0.08712137, ..., 0.        , 0.        ,
         0.        ])),
 (152,
  array([0.06388766, 0.06681531, 0.10182663, ..., 0.02817181, 0.        ,
         0.        ])),
 (153,
  array([0.08656873, 0.04526787, 0.06898831, ..., 0.11451967, 0.        ,
         0.        ])),
 (154,
  array([0.03314968, 0.03466876, 0.0352235 , ..., 0.0877058 , 0.        ,
         0.03140371])),
 (155,
  array([0.        , 0.        , 0.06956083, ..., 0.01924501, 0.02122382,
         0.02067246])),
 (156,
  array([0.06658451, 0.04642383, 0.02358333, ..., 0.01957401, 0.        ,
         0.        ])),
 (157,
  array([0.10573611, 0.07372098, 0.07490059, ..., 0.03108349, 0.        ,
         0.        ])),
 (158,
  array([0.15289416, 0.07995027, 0.08122955, ..., 0.        , 0.        ,
         0.        ])),
 (159,
  array([0.06761234, 0.07071068, 0.03592106, ..., 0.        , 0.        ,
         0.        ])),
 (160,
  array([0.09694584, 0.06083303, 0.08240856, ..., 0.03419928, 0.05657357,
         0.11020775])),
 (161,
  array([0.03524537, 0.03686049, 0.        , ..., 0.        , 0.        ,
         0.        ])),
 (162,
  array([0.03688556, 0.07715167, 0.07838618, ..., 0.03253   , 0.        ,
         0.        ])),
 (163,
  array([0.0541332 , 0.02830693, 0.0862796 , ..., 0.0238705 , 0.        ,
         0.        ])),
 (164,
  array([0.09416472, 0.09847982, 0.13340747, ..., 0.05536365, 0.06105625,
         0.        ])),
 (165,
  array([0.04984448, 0.0260643 , 0.05296271, ..., 0.06593805, 0.        ,
         0.        ])),
 (166,
  array([0.11952286, 0.0625    , 0.12700013, ..., 0.07905694, 0.        ,
         0.        ])),
 (167,
  array([0.06900656, 0.10825318, 0.07332356, ..., 0.06085806, 0.0335578 ,
         0.        ])),
 (168,
  array([0.16035675, 0.1118034 , 0.05679618, ..., 0.02357023, 0.02599376,
         0.02531848])),
 (169,
  array([0.11952286, 0.1       , 0.07620008, ..., 0.0421637 , 0.        ,
         0.        ])),
 (170,
  array([0.09200874, 0.04811252, 0.1710883 , ..., 0.06085806, 0.02237187,
         0.        ])),
 (171,
  array([0.02942449, 0.12309149, 0.03126527, ..., 0.        , 0.        ,
         0.        ])),
 (172,
  array([0.15118579, 0.07905694, 0.04016097, ..., 0.1       , 0.07352146,
         0.        ])),
 (173,
  array([0.0243975 , 0.02551552, 0.02592379, ..., 0.04303315, 0.        ,
         0.02311251])),
 (174,
  array([0.111154  , 0.05812382, 0.05905386, ..., 0.        , 0.02702703,
         0.05264981])),
 (175,
  array([0.05155393, 0.05391639, 0.0547791 , ..., 0.        , 0.02507061,
         0.        ])),
 (176,
  array([0.03086067, 0.06454972, 0.06558258, ..., 0.05443311, 0.        ,
         0.        ])),
 (177,
  array([0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.03774257])),
 (178,
  array([0.02577696, 0.08087458, 0.02738955, ..., 0.04546629, 0.05014122,
         0.04883863])),
 (179,
  array([0.07559289, 0.03952847, 0.1204829 , ..., 0.06666667, 0.        ,
         0.        ])),
 (180,
  array([0.02390457, 0.025     , 0.12700013, ..., 0.0421637 , 0.02324953,
         0.02264554])),
 (181,
  array([0.02344036, 0.04902903, 0.02490677, ..., 0.02067246, 0.        ,
         0.02220578])),
 (182,
  array([0.1069045 , 0.08385255, 0.08519428, ..., 0.07071068, 0.07798129,
         0.02531848])),
 (183,
  array([0.07466534, 0.05856516, 0.09917044, ..., 0.01646216, 0.        ,
         0.        ])),
 (184,
  array([0.18257419, 0.05455447, 0.        , ..., 0.02300219, 0.02536731,
         0.02470831])),
 (185,
  array([0.055577  , 0.02906191, 0.02952693, ..., 0.        , 0.02702703,
         0.02632491])),
 (186,
  array([0.04069785, 0.04256283, 0.06486581, ..., 0.03589213, 0.        ,
         0.        ])),
 (187,
  array([0.14085904, 0.20623948, 0.11973687, ..., 0.0248452 , 0.08219949,
         0.        ])),
 (188,
  array([0.0225877 , 0.02362278, 0.12000384, ..., 0.        , 0.        ,
         0.02139802])),
 (189,
  array([0.08199201, 0.04287465, 0.04356068, ..., 0.07231015, 0.        ,
         0.        ])),
 (190,
  array([0.08386279, 0.15348515, 0.11138648, ..., 0.07396003, 0.04078237,
         0.01986145])),
 (191,

In [212]:
def func(genre, n = 10):
    index = df[df['genres'].apply(lambda x : genre in x)][['title', 'vote_average']]
    # distances = sorted(list(enumerate(similarity)), reverse = True, key = lambda x : x[1])
    # for i in distances[1: : 6]:
    #     print(df.iloc[i[0]].title)
    result = index.sort_values('vote_average', ascending = False)

    return result[['title', 'vote_average']].head(n)

In [216]:
func('Thriller')

                         title  vote_average
3235              Pulp Fiction           8.3
65             The Dark Knight           8.2
2172                    Psycho           8.2
1555                     Se7en           8.1
3457        The Usual Suspects           8.1
96                   Inception           8.1
2093  The Silence of the Lambs           8.1
2286               The Shining           8.1
2762                      Room           8.1
3576                   Memento           8.1